name: Invitation to the GitHub Community Organization
description: I would like to be part of the Py-Contributors community
title: "Please invite me to the GitHub Community Organization"
labels: [invite me to the organisation]
body:
  - type: input
    id: name
    attributes:
      label: Name
      placeholder: Insert your name here
    validations:
      required: true
  - type: textarea
    id: Additional
    attributes:
      label: Additional Context
      description: How did you learn about Py-Contributors? Why do you want to join us? 
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        **You can also join our Discord community [here](https://discord.gg/JfbK3bS)**
        **Feel free to check out other cool repositories of the Py-Contributors Community [here](https://github.com/orgs/Py-Contributors)**
